---
# Install Zabbix agent dependencies
- name: "Install Zabbix agent dependencies"
  action: ${ansible_pkg_mgr} pkg=${item} state=installed update-cache=yes
  when_boolean: ${with_zabbix_agent}
  with_items: ${zabbix_agent.dependencies}
  tags:
    - zabbix_agent

# Fetch .deb file from repository
- name: "Fetch Debian package: ${zabbix_agent.debian_package}"
  action: get_url url=${zabbix.debian_repo}/${zabbix_agent.debian_package} dest=${zabbix.tmp_dir} mode=0440 owner=root group=root
  when_boolean: ${with_zabbix_agent}
  tags:
    - zabbix_agent

# Install Zabbix agent deb file
- name: "Install Zabbix agent: ${zabbix_agent.debian_package}"
  action: shell dpkg -i -E ${zabbix.tmp_dir}/${zabbix_agent.debian_package} 2>&1 | grep skipping | wc -l
  register: agent_installed
  when_boolean: ${with_zabbix_agent}
  tags:
    - zabbix_agent

# Override defaults from Zabbix agent config file
- name: "Put custom Zabbix agent settings in include dir"
  action: template src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf.d/custom.conf owner=root group=root mode=0640
  when_boolean: ${with_zabbix_agent}
  notify:
    - "Restart Zabbix agent"
  tags:
    - zabbix_agent

# Ensure Zabbix agent is running
- name: "Ensure Zabbix agent is running"
  action: service name=${zabbix_agent.name} state=started
  when_boolean: ${with_zabbix_agent}
  tags:
    - zabbix_agent
