---
# Execute some tests first
- include: checks.yml

# Add Zabbix repository
- include: repo.yml
  when: ansible_distribution == "Debian"

# Install the Zabbix agent
- include: agent.yml
  when: with_zabbix_agent

# Install the Zabbix server
- include: server.yml
  when: with_zabbix_server

# Install the Zabbix webfronted using Apache
- include: web.yml
  when: with_zabbix_web

# Install the Zabbix java gateway
- include: java.yml
  when: with_zabbix_java
