---
#update cache
- name: "Update cache"
  action: apt update_cache=yes

#Make sure apt_add_repository is installed
- name: "Install python-software-properties"
  apt: pkg=python-software-properties state=present

- name: "Add zabbix repo key to server"
  apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present

#add repository to sources
- name: "add official zabbix repo to sources"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/2.0/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main non-free contrib"
  tags:
    - zabbix_repo