---
# Prepare database setup
- include: db.yml

# Install Zabbix server dependencies
- name: "Install Zabbix server dependencies"
  action: ${ansible_pkg_mgr} pkg={{ item }} state=installed update-cache=yes
  with_items: zabbix_server.dependencies

# Install Zabbix server deb file
- name: "Install Zabbix server"
  action: ${ansible_pkg_mgr} pkg={{ zabbix_server.package }} state=installed update-cache=yes
  register: server_installed

# Check if Zabbix db is empty
- name: "Check if Zabbix db is empty"
  action: shell mysql -h {{ mysql.host }} -u {{ mysql.admin_user }} --password={{ mysql.admin_password }} {{ zabbix_server.db.name }} -e "SHOW TABLES" | wc -l
  register: zabbix_tables

# Execute db installation scripts
- name: "Execute Zabbix SQL files"
  action: shell zcat /usr/share/zabbix-server-mysql/{{ item }}.sql.gz | mysql -u{{ zabbix_server.db.user }} -p{{ zabbix_server.db.pass }} {{ zabbix_server.db.name }}
  when: with_zabbix_server and zabbix_tables.stdout == "0"
  with_items: zabbix_server.db.sql_files

# Create Zabbix server include directory
- name: "Create Zabbix server include directory"
  action: file path=/etc/zabbix/zabbix_server.conf.d group=root owner=root mode=0750 state=directory

# Enable Zabbix server include directory
- name: "Enable Zabbix server include directory"
  action: lineinfile dest=/etc/zabbix/zabbix_server.conf regexp="^.*Include=/etc/zabbix/zabbix_server.conf.d/" line="Include=/etc/zabbix/zabbix_server.conf.d/"

# Enable Zabbix server in /etc/default/zabbix-server
- name: "Enable Zabbix server in /etc/default/zabbix-server"
  action: lineinfile dest=/etc/default/zabbix-server regexp="^START=" line="START=yes"

# Override defaults from Zabbix server config file
- name: "Put custom Zabbix server settings in include dir"
  action: template src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf.d/custom.conf owner=root group=root mode=0640
  notify:
    - "Restart Zabbix server"

# Ensure Zabbix server is running
- name: "Ensure Zabbix server is running"
  action: service name={{ zabbix_server.service }} state=started